//! The GeoNames subset Narrow ships: every country, every first-level
//! administrative region, and every place of more than 15,000 people (or a
//! capital), each with its IANA time zones, its GeoNames id, and its names
//! in English and in the country's own languages.
//!
//! The data is generated by `scripts/geonames/generate.py` from the
//! GeoNames dump and compiled into the binary (see
//! `data/geonames/README.md`): nothing is downloaded at build time, at
//! startup or per posting. It is read once, on first use, into hash
//! indexes, so a lookup is one hash of the name.
//!
//! This module only finds entries; deciding what a name means (which of
//! several "Cambridge"s, a country or a state called "Georgia") is
//! [`crate::geo`]'s job, from these candidates.
//!
//! Data © GeoNames (<https://www.geonames.org>), licensed under Creative
//! Commons Attribution 4.0.

use std::collections::HashMap;
use std::sync::LazyLock;

use chrono_tz::Tz;
use jobhunt_core::text::search_key;
use unicode_normalization::UnicodeNormalization;

/// A GeoNames id (<https://www.geonames.org/2643743> is London).
pub type GeoId = u32;

static COUNTRIES_TSV: &str = include_str!("../data/geonames/countries.tsv");
static ADMIN1_TSV: &str = include_str!("../data/geonames/admin1.tsv");
static CITIES_TSV: &str = include_str!("../data/geonames/cities.tsv");

/// A country as GeoNames lists it.
#[derive(Debug)]
pub struct GeoCountry {
    /// ISO 3166-1 alpha-2.
    pub code: &'static str,
    pub name: &'static str,
    /// GeoNames continent code: `AF`, `AN`, `AS`, `EU`, `NA`, `OC`, `SA`.
    pub continent: &'static str,
    pub population: u64,
    /// Every IANA zone of the country.
    pub zones: Vec<Tz>,
}

/// A first-level administrative region (a state, province or region).
#[derive(Debug)]
pub struct Admin1 {
    pub id: GeoId,
    pub country: &'static str,
    /// GeoNames' code within the country (ISO for the US, FIPS for most).
    pub code: &'static str,
    pub name: &'static str,
    /// The people of its listed places: a weight for telling names apart,
    /// not a census.
    pub population: u64,
    /// The zones of its listed places; empty when none is listed.
    pub zones: Vec<Tz>,
}

/// A populated place.
#[derive(Debug)]
pub struct City {
    pub id: GeoId,
    pub country: &'static str,
    /// The region it is in, when GeoNames lists one.
    pub admin1: Option<GeoId>,
    pub population: u64,
    pub zone: Tz,
    pub name: &'static str,
}

/// What a name can refer to.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Entry {
    Country(usize),
    Admin1(usize),
    City(usize),
}

/// The loaded subset and its indexes.
#[derive(Debug)]
pub struct Gazetteer {
    pub countries: Vec<GeoCountry>,
    pub admin1: Vec<Admin1>,
    pub cities: Vec<City>,
    country_by_code: HashMap<&'static str, usize>,
    admin1_by_id: HashMap<GeoId, usize>,
    city_by_id: HashMap<GeoId, usize>,
    /// Every name, by [`fold_key`].
    names: HashMap<String, Vec<Entry>>,
}

/// The subset, read on first use.
pub static GAZETTEER: LazyLock<Gazetteer> = LazyLock::new(Gazetteer::load);

/// A name as the indexes key it: [`search_key`] without diacritics, so
/// "São Paulo", "Sao Paulo" and "SÃO PAULO" are one key, while "ł" and
/// other letters without a decomposition stay (GeoNames' ASCII names
/// cover those: "Wroclaw").
pub fn fold_key(text: &str) -> String {
    if text.is_ascii() {
        return search_key(text);
    }
    let stripped: String = text
        .nfd()
        .filter(|c| !unicode_normalization::char::is_combining_mark(*c))
        .collect();
    search_key(&stripped)
}

fn rows(tsv: &'static str) -> impl Iterator<Item = Vec<&'static str>> {
    tsv.lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
        .map(|l| l.split('\t').collect())
}

fn list(field: Option<&&'static str>) -> impl Iterator<Item = &'static str> {
    field
        .copied()
        .unwrap_or_default()
        .split('|')
        .filter(|s| !s.is_empty())
}

fn zones(field: Option<&&'static str>, known: &mut HashMap<&'static str, Option<Tz>>) -> Vec<Tz> {
    list(field)
        .filter_map(|name| *known.entry(name).or_insert_with(|| name.parse().ok()))
        .collect()
}

impl Gazetteer {
    fn load() -> Self {
        let mut known: HashMap<&'static str, Option<Tz>> = HashMap::new();
        let mut names: HashMap<String, Vec<Entry>> = HashMap::with_capacity(100_000);
        let mut add = |name: &str, entry: Entry| {
            let key = fold_key(name);
            if key.is_empty() {
                return;
            }
            let entries = names.entry(key).or_default();
            if !entries.contains(&entry) {
                entries.push(entry);
            }
        };

        let mut countries = Vec::new();
        let mut country_by_code = HashMap::new();
        for r in rows(COUNTRIES_TSV) {
            let [code, name, continent, population, ..] = r[..] else {
                continue;
            };
            let entry = Entry::Country(countries.len());
            add(name, entry);
            for other in list(r.get(5)) {
                add(other, entry);
            }
            country_by_code.insert(code, countries.len());
            countries.push(GeoCountry {
                code,
                name,
                continent,
                population: population.parse().unwrap_or(0),
                zones: zones(r.get(4), &mut known),
            });
        }

        let mut admin1 = Vec::new();
        let mut admin1_by_id = HashMap::new();
        let mut admin1_by_code: HashMap<(&str, &str), GeoId> = HashMap::new();
        for r in rows(ADMIN1_TSV) {
            let [id, country, code, name, population, ..] = r[..] else {
                continue;
            };
            let Ok(id) = id.parse::<GeoId>() else {
                continue;
            };
            let entry = Entry::Admin1(admin1.len());
            add(name, entry);
            for other in list(r.get(6)) {
                add(other, entry);
            }
            admin1_by_id.insert(id, admin1.len());
            admin1_by_code.insert((country, code), id);
            admin1.push(Admin1 {
                id,
                country,
                code,
                name,
                population: population.parse().unwrap_or(0),
                zones: zones(r.get(5), &mut known),
            });
        }

        let mut cities = Vec::new();
        let mut city_by_id = HashMap::new();
        for r in rows(CITIES_TSV) {
            let [id, country, admin, population, zone, name, ..] = r[..] else {
                continue;
            };
            let (Ok(id), Some(zone)) = (
                id.parse::<GeoId>(),
                *known.entry(zone).or_insert_with(|| zone.parse().ok()),
            ) else {
                continue;
            };
            let entry = Entry::City(cities.len());
            add(name, entry);
            for other in list(r.get(6)) {
                add(other, entry);
            }
            city_by_id.insert(id, cities.len());
            cities.push(City {
                id,
                country,
                admin1: admin1_by_code.get(&(country, admin)).copied(),
                population: population.parse().unwrap_or(0),
                zone,
                name,
            });
        }
        Self {
            countries,
            admin1,
            cities,
            country_by_code,
            admin1_by_id,
            city_by_id,
            names,
        }
    }

    /// Everything a name can refer to, by [`fold_key`].
    pub fn lookup(&self, name: &str) -> &[Entry] {
        self.names.get(&fold_key(name)).map_or(&[], Vec::as_slice)
    }

    pub fn country(&self, code: &str) -> Option<&GeoCountry> {
        self.country_by_code
            .get(code)
            .and_then(|i| self.countries.get(*i))
    }

    pub fn admin1(&self, id: GeoId) -> Option<&Admin1> {
        self.admin1_by_id.get(&id).and_then(|i| self.admin1.get(*i))
    }

    pub fn city(&self, id: GeoId) -> Option<&City> {
        self.city_by_id.get(&id).and_then(|i| self.cities.get(*i))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_every_file() {
        let g = &*GAZETTEER;
        assert!(g.countries.len() > 240, "{}", g.countries.len());
        assert!(g.admin1.len() > 3_500, "{}", g.admin1.len());
        assert!(g.cities.len() > 30_000, "{}", g.cities.len());
        // Every zone GeoNames names is one the IANA database knows, and
        // every country has one, but for codes no longer in use
        // (Netherlands Antilles, Serbia and Montenegro) and uninhabited
        // islands (Bouvet, Heard and McDonald).
        for c in &g.countries {
            assert!(
                !c.zones.is_empty() || ["AN", "CS", "BV", "HM"].contains(&c.code),
                "{} has zones",
                c.code
            );
        }
        let column = |tsv: &'static str, n: usize| {
            rows(tsv).flat_map(move |r| list(r.get(n)).collect::<Vec<_>>())
        };
        for zone in column(COUNTRIES_TSV, 4).chain(column(ADMIN1_TSV, 5)) {
            assert!(zone.parse::<Tz>().is_ok(), "{zone} is an IANA zone");
        }
    }

    #[test]
    fn folds_diacritics_and_keeps_native_names() {
        assert_eq!(fold_key("São Paulo"), "sao paulo");
        assert_eq!(fold_key("SÃO PAULO"), "sao paulo");
        assert_eq!(fold_key("Zürich"), "zurich");
        let g = &*GAZETTEER;
        let city = |name: &str| -> Vec<(&str, &str)> {
            g.lookup(name)
                .iter()
                .filter_map(|e| match e {
                    Entry::City(i) => Some((g.cities[*i].name, g.cities[*i].country)),
                    _ => None,
                })
                .collect()
        };
        assert!(city("Sao Paulo").contains(&("São Paulo", "BR")));
        assert!(city("Lisboa").contains(&("Lisbon", "PT")));
        assert!(city("München").contains(&("Munich", "DE")));
        assert!(city("Muenchen").contains(&("Munich", "DE")));
        assert!(city("Wroclaw").iter().any(|(_, c)| *c == "PL"));
        // A city keeps its own IANA zone: Dourados is on UTC-4, not
        // Brasília time.
        let dourados = g
            .lookup("Dourados")
            .iter()
            .find_map(|e| match e {
                Entry::City(i) => Some(&g.cities[*i]),
                _ => None,
            })
            .unwrap();
        assert_eq!(dourados.zone.name(), "America/Campo_Grande");
        assert_eq!(
            g.admin1(dourados.admin1.unwrap()).unwrap().name,
            "Mato Grosso do Sul"
        );
    }
}
