// TypeScript types for every body of the JobHunt API, generated from the
// JSON Schema the Rust server's types produce
// (crates/jobhunt-cloud/tests/api_schema.rs). `--check` fails when the
// committed file is stale, so the web app cannot drift from the server.
import { readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";

const here = new URL("../src/lib/", import.meta.url);
const schema = JSON.parse(await readFile(new URL("api-schema.json", here), "utf8"));
const banner =
  "/* Generated by scripts/generate-types.mjs from api-schema.json (the Rust API types).\n" +
  " * Do not edit: run `npm run types` after the schema changes. */";
const output = await compile(schema, "JobHuntApi", {
  bannerComment: banner,
  unreachableDefinitions: true,
  additionalProperties: false,
  strictIndexSignatures: true,
  format: true,
  style: { semi: true, singleQuote: false, printWidth: 100 },
});
const target = new URL("api-types.ts", here);
if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    console.error("src/lib/api-types.ts is out of date: run `npm run types`.");
    process.exit(1);
  }
} else {
  await writeFile(target, output);
}
