#!/usr/bin/env python3
"""Builds Narrow's GeoNames subset from a local copy of the GeoNames dump.

    ./scripts/geonames/download.sh /tmp/geonames      # fetch the inputs once
    python3 scripts/geonames/generate.py /tmp/geonames

Reads these files from the given directory (see
https://download.geonames.org/export/dump/readme.txt for their formats):

    countryInfo.txt       countries: ISO codes, names, continents, populations
    timeZones.txt         the IANA time zones of every country
    admin1CodesASCII.txt  first-level administrative regions (states, provinces)
    cities15000.txt       places with more than 15,000 people, or capitals
    alternateNamesV2.txt  names in other languages (English and each country's
                          own languages are kept)

and writes, under crates/jobhunt-eligibility/data/geonames/:

    countries.tsv  code, name, continent, population, zones, other names
    admin1.tsv     geonameid, country, code, name, population, zones, other names
    cities.tsv     geonameid, country, admin1, population, zone, name, other names

Lists inside a field are separated by "|". Every row and list is sorted, and
each file's header records the SHA-256 of the inputs it came from, so the same
inputs always produce byte-identical files. Nothing here runs at build time or
when Narrow starts: the generated files are committed, and Narrow reads them
from its own binary.

GeoNames data is licensed under Creative Commons Attribution 4.0
(https://creativecommons.org/licenses/by/4.0/); the generated files carry the
attribution in their headers.
"""

from __future__ import annotations

import hashlib
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "crates/jobhunt-eligibility/data/geonames"

INPUTS = [
    "countryInfo.txt",
    "timeZones.txt",
    "admin1CodesASCII.txt",
    "cities15000.txt",
    "alternateNamesV2.txt",
]

ATTRIBUTION = (
    "# Derived from GeoNames (https://www.geonames.org), licensed under CC BY 4.0\n"
    "# (https://creativecommons.org/licenses/by/4.0/). Generated by\n"
    "# scripts/geonames/generate.py; do not edit by hand.\n"
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def rows(path: Path):
    with path.open(encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            yield line.rstrip("\n").split("\t")


def clean(text: str) -> str:
    """One line of text, without the characters the TSV format reserves."""
    return " ".join(text.replace("|", " ").split())


def latin(name: str) -> bool:
    """Written in the Latin script (with or without diacritics)."""
    for c in name:
        if c.isalpha():
            decomposed = unicodedata.normalize("NFD", c)[0]
            if not ("a" <= decomposed.lower() <= "z") and "LATIN" not in unicodedata.name(c, ""):
                return False
        elif not (c in " -'’.()" or c.isspace()):
            return False
    return True


def keep_alternate(name: str) -> bool:
    """A name worth matching: Latin script, not a code, no digits."""
    name = name.strip()
    if len(name) < 3 or any(c.isdigit() for c in name):
        return False
    if name.isupper() and len(name) <= 4:
        return False  # IATA and other codes ("LON", "YXU")
    return latin(name)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    missing = [name for name in INPUTS if not (src / name).is_file()]
    if missing:
        print(f"missing in {src}: {', '.join(missing)}", file=sys.stderr)
        return 1
    header = ATTRIBUTION + "".join(
        f"# input {name} sha256 {sha256(src / name)}\n" for name in INPUTS
    )

    # Countries.
    countries: dict[str, dict] = {}
    country_by_geonameid: dict[str, str] = {}
    for r in rows(src / "countryInfo.txt"):
        code, name, population, continent = r[0], r[4], r[7], r[8]
        languages = {l.split("-")[0] for l in r[15].split(",") if l}
        geonameid = r[16]
        countries[code] = {
            "name": clean(name),
            "continent": continent,
            "population": int(population or 0),
            "languages": languages | {"en"},
            "zones": set(),
            "names": set(),
        }
        if geonameid:
            country_by_geonameid[geonameid] = code

    first = True
    for r in rows(src / "timeZones.txt"):
        if first:  # the column header
            first = False
            continue
        code, zone = r[0], r[1]
        if code in countries:
            countries[code]["zones"].add(zone)

    # First-level administrative regions.
    admin1: dict[str, dict] = {}  # "BR.27" -> …
    admin1_by_geonameid: dict[str, str] = {}
    for r in rows(src / "admin1CodesASCII.txt"):
        key, name, ascii_name, geonameid = r[0], r[1], r[2], r[3]
        country, code = key.split(".", 1)
        if country not in countries:
            continue
        admin1[key] = {
            "geonameid": int(geonameid),
            "country": country,
            "code": code,
            "name": clean(name),
            "population": 0,
            "zones": set(),
            "names": {clean(ascii_name)} - {clean(name)},
        }
        admin1_by_geonameid[geonameid] = key

    # Cities.
    cities: dict[str, dict] = {}
    for r in rows(src / "cities15000.txt"):
        geonameid, name, ascii_name = r[0], r[1], r[2]
        country, admin1_code, population, zone = r[8], r[10], r[14], r[17]
        if country not in countries or not zone:
            continue
        population = int(population or 0)
        admin_key = f"{country}.{admin1_code}"
        if admin_key in admin1:
            admin1[admin_key]["population"] += population
            admin1[admin_key]["zones"].add(zone)
        else:
            admin1_code = ""
        cities[geonameid] = {
            "country": country,
            "admin1": admin1_code,
            "population": population,
            "zone": zone,
            "name": clean(name),
            "names": {clean(ascii_name)} - {clean(name)},
        }

    # A country timeZones.txt doesn't cover (Kosovo) keeps its places' zones.
    for city in cities.values():
        country = countries[city["country"]]
        if not country["zones"] or country.get("zones_from_cities"):
            country["zones_from_cities"] = True
            country["zones"].add(city["zone"])

    # Alternate names: English and the country's own languages; not
    # historic, colloquial, codes, links or other scripts.
    with (src / "alternateNamesV2.txt").open(encoding="utf-8") as f:
        for line in f:
            r = line.rstrip("\n").split("\t")
            geonameid, language, name = r[1], r[2], r[3]
            historic = len(r) > 7 and r[7] == "1"
            colloquial = len(r) > 6 and r[6] == "1"
            if historic or colloquial or not keep_alternate(name):
                continue
            if geonameid in cities:
                target = cities[geonameid]
                country = target["country"]
            elif geonameid in admin1_by_geonameid:
                target = admin1[admin1_by_geonameid[geonameid]]
                country = target["country"]
            elif geonameid in country_by_geonameid:
                country = country_by_geonameid[geonameid]
                target = countries[country]
            else:
                continue
            if language.split("-")[0] not in countries[country]["languages"]:
                continue
            name = clean(name)
            if name != target["name"]:
                target["names"].add(name)

    OUT.mkdir(parents=True, exist_ok=True)
    joined = lambda items: "|".join(sorted(i for i in items if i))

    with (OUT / "countries.tsv").open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write("# code\tname\tcontinent\tpopulation\tzones\tother names\n")
        for code in sorted(countries):
            c = countries[code]
            f.write(
                f"{code}\t{c['name']}\t{c['continent']}\t{c['population']}\t"
                f"{joined(c['zones'])}\t{joined(c['names'])}\n"
            )

    with (OUT / "admin1.tsv").open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write("# geonameid\tcountry\tcode\tname\tpopulation\tzones\tother names\n")
        for a in sorted(admin1.values(), key=lambda a: a["geonameid"]):
            f.write(
                f"{a['geonameid']}\t{a['country']}\t{a['code']}\t{a['name']}\t"
                f"{a['population']}\t{joined(a['zones'])}\t{joined(a['names'])}\n"
            )

    with (OUT / "cities.tsv").open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write("# geonameid\tcountry\tadmin1\tpopulation\tzone\tname\tother names\n")
        for geonameid in sorted(cities, key=int):
            c = cities[geonameid]
            f.write(
                f"{geonameid}\t{c['country']}\t{c['admin1']}\t{c['population']}\t"
                f"{c['zone']}\t{c['name']}\t{joined(c['names'])}\n"
            )

    for name in ["countries.tsv", "admin1.tsv", "cities.tsv"]:
        path = OUT / name
        print(f"{path.relative_to(OUT.parents[3])}: {path.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
