/* Generated by scripts/generate-types.mjs from api-schema.json (the Rust API types).
 * Do not edit: run `npm run types` after the schema changes. */

/**
 * Whether JobHunt recommends spending time on it now.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Recommendation".
 */
export type Recommendation =
  "recommended" | "verify_first" | "eligibility_unclear" | "not_recommended";
/**
 * How worth the person's time a job looks. Deliberately coarse: there is
 * no percentage.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FitTier".
 */
export type FitTier = "strong_fit" | "worth_reviewing" | "maybe" | "low_priority";
/**
 * Whether the person appears able to work the job.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EligibilityStatus".
 */
export type EligibilityStatus =
  ("eligible" | "uncertain" | "ineligible") | "conditional" | "not_checked";
/**
 * Why a fact may be used.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "UsableBasis".
 */
export type UsableBasis = "confirmed_by_you" | "entered_by_you" | "quoted_from_resume";
/**
 * How recent the last successful verification is.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Freshness".
 */
export type Freshness = "fresh" | "aging" | "stale";
/**
 * What JobHunt believes about the listing, from verification and
 * discovery.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "VerificationState".
 */
export type VerificationState =
  | "verified_active"
  | "verified_closed"
  | "closed_by_discovery"
  | "could_not_verify"
  | "not_verified";
/**
 * A decision about claims.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ClaimDecision".
 */
export type ClaimDecision = "confirm" | "reject" | "reset";
/**
 * Feedback actions accepted by the API.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedbackInput".
 */
export type FeedbackInput =
  ("save" | "unsave" | "reject" | "applied" | "interview" | "offer" | "like" | "dislike") | "seen";
/**
 * Liked or disliked, independent of the pipeline stage.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SentimentView".
 */
export type SentimentView = "liked" | "disliked";
/**
 * Where the opportunity is in the person's pipeline.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PipelineStage".
 */
export type PipelineStage =
  "unseen" | "seen" | "saved" | "rejected" | "applied" | "interviewing" | "offer";
/**
 * Whether the job can be applied to, as last checked.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ApplicationState".
 */
export type ApplicationState = "active" | "closed" | "unavailable" | "unknown";
/**
 * The listing state one verification attempt found.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ListingState".
 */
export type ListingState = "active" | "closed" | "unreachable" | "ambiguous" | "unknown";
/**
 * A question about a preference read from someone's words, with the
 * reading it would correct.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Clarify".
 */
export type Clarify =
  | {
      amount: number;
      /**
       * `employment` or `contract`, when the words said.
       */
      applies_to?: string | null;
      /**
       * As read: `minimum` or `target`.
       */
      bound: string;
      /**
       * As read; absent when the words didn't say (never assumed).
       */
      currency?: string | null;
      kind: "pay";
      /**
       * `year`, `month`, `day` or `hour`, as read.
       */
      period: string;
    }
  | {
      kind: "size";
      /**
       * As read: `small_team` or `small_company`.
       */
      value: string;
    }
  | {
      /**
       * The same preference as an input; answering sets it with the
       * chosen stance (`require` or `want`) in place of this reading.
       */
      input:
        | {
            kind: "role";
            role: string;
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          }
        | {
            /**
             * Applies to employment only or contracts only (both when absent).
             */
            applies_to?: ArrangementInput | null;
            /**
             * ISO 4217 code (USD, EUR, BRL). Never assumed.
             */
            currency: string;
            kind: "compensation";
            minimum?: number | null;
            /**
             * A pay period.
             */
            period?: "year" | "month" | "day" | "hour";
            target?: number | null;
          }
        | {
            kind: "work_mode";
            mode: WorkModeInput;
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          }
        | {
            kind: "location";
            place: string;
          }
        | {
            kind: "region";
            region: string;
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          }
        | {
            kind: "timezone";
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
            zone: string;
          }
        | {
            kind: "relocation";
            only_to?: string[];
            willing: boolean;
          }
        | {
            kind: "work_setup";
            setup: WorkSetupInput;
          }
        | {
            kind: "unknown_pay";
            show: boolean;
          }
        | {
            kind: "unclear_eligibility";
            show: boolean;
          }
        | {
            kind: "sponsorship";
            needed: boolean;
          }
        | {
            kind: "authorized_in";
            place: string;
          }
        | {
            engagement: EngagementInput;
            kind: "engagement";
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          }
        | {
            company: string;
            kind: "company";
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          }
        | {
            domain: string;
            kind: "domain";
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          }
        | {
            aspect: string;
            kind: "work_style";
            /**
             * How strongly a preference holds.
             */
            stance?: "require" | "want" | "accept" | "avoid";
          };
      kind: "importance";
      /**
       * The preference, readable: "remote work", "startups".
       */
      value: string;
    };
/**
 * Which arrangement a pay preference applies to.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ArrangementInput".
 */
export type ArrangementInput = "employment" | "contract";
/**
 * Remote, hybrid or on-site.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "WorkModeInput".
 */
export type WorkModeInput = "remote" | "hybrid" | "onsite";
/**
 * How the person wants to work, as one answer. Each is stored as the
 * work-mode preferences it means, replacing any others:
 *
 * | Answer | Stored | Layer |
 * | --- | --- | --- |
 * | `remote_only` | remote: required | requirement: hybrid or on-site jobs are a stated conflict |
 * | `prefer_remote` | remote: wanted | preference: ranking only |
 * | `hybrid_okay` | remote or hybrid: required | requirement: on-site jobs are a stated conflict |
 * | `onsite_okay` | on-site: acceptable | preference: nothing is ruled out |
 * | `no_preference` | nothing | — |
 *
 * Work setup is not relocation (a separate answer), nor where the person
 * may legally work.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "WorkSetupInput".
 */
export type WorkSetupInput =
  "remote_only" | "prefer_remote" | "hybrid_okay" | "onsite_okay" | "no_preference";
/**
 * Hired as an employee or as a contractor (B2B, freelance).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EngagementInput".
 */
export type EngagementInput = "employee" | "contractor";
/**
 * A change to the taste profile.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteAction".
 */
export type TasteAction =
  | {
      action: "describe";
      text: string;
    }
  | {
      action: "reinterpret";
    }
  | {
      action: "confirm";
      ids?: string[];
    }
  | {
      action: "correct";
      id: string;
      polarity?: PolarityInput | null;
      text?: string | null;
    }
  | {
      action: "neutral";
      id: string;
    }
  | {
      action: "remove";
      id: string;
    }
  | {
      action: "add";
      text: string;
    };
/**
 * Which way a statement leans, as given.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PolarityInput".
 */
export type PolarityInput = ("prefer" | "open" | "avoid") | "neutral";
/**
 * One precise preference.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PreferenceInput".
 */
export type PreferenceInput =
  | {
      kind: "role";
      role: string;
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    }
  | {
      /**
       * Applies to employment only or contracts only (both when absent).
       */
      applies_to?: ArrangementInput | null;
      /**
       * ISO 4217 code (USD, EUR, BRL). Never assumed.
       */
      currency: string;
      kind: "compensation";
      minimum?: number | null;
      /**
       * A pay period.
       */
      period?: "year" | "month" | "day" | "hour";
      target?: number | null;
    }
  | {
      kind: "work_mode";
      mode: WorkModeInput;
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    }
  | {
      kind: "location";
      place: string;
    }
  | {
      kind: "region";
      region: string;
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    }
  | {
      kind: "timezone";
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
      zone: string;
    }
  | {
      kind: "relocation";
      only_to?: string[];
      willing: boolean;
    }
  | {
      kind: "work_setup";
      setup: WorkSetupInput;
    }
  | {
      kind: "unknown_pay";
      show: boolean;
    }
  | {
      kind: "unclear_eligibility";
      show: boolean;
    }
  | {
      kind: "sponsorship";
      needed: boolean;
    }
  | {
      kind: "authorized_in";
      place: string;
    }
  | {
      engagement: EngagementInput;
      kind: "engagement";
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    }
  | {
      company: string;
      kind: "company";
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    }
  | {
      domain: string;
      kind: "domain";
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    }
  | {
      aspect: string;
      kind: "work_style";
      /**
       * How strongly a preference holds.
       */
      stance?: "require" | "want" | "accept" | "avoid";
    };
/**
 * Why an item is on the feed.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedReason".
 */
export type FeedReason = "new" | "changed";
/**
 * A pay period.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PeriodInput".
 */
export type PeriodInput = "year" | "month" | "day" | "hour";
/**
 * Whether to read job boards before answering.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "RefreshInput".
 */
export type RefreshInput = "auto" | "always" | "never";
/**
 * How strongly a preference holds.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "StanceInput".
 */
export type StanceInput = "require" | "want" | "accept" | "avoid";

/**
 * Every body the JobHunt HTTP API (/api/v1) accepts or answers with. Generated from the Rust types by crates/jobhunt-cloud/tests/api_schema.rs; do not edit.
 */
export interface JobHuntApi {
  AccountView?: AccountView;
  ApplicationContext?: ApplicationContext;
  AuthConfigView?: AuthConfigView;
  ClaimDecisionResult?: ClaimDecisionResult;
  ClaimReview?: ClaimReview;
  ConfirmEmailRequest?: ConfirmEmailRequest;
  CreateTokenRequest?: CreateTokenRequest;
  CreatedToken?: CreatedToken;
  DecideClaimsRequest?: DecideClaimsRequest;
  DevTokenResponse?: DevTokenResponse;
  ErrorBody?: ErrorBody;
  FeedView?: FeedView;
  FeedbackRequest?: FeedbackRequest;
  FeedbackResult?: FeedbackResult;
  GithubImportRequest?: GithubImportRequest;
  JobDetail?: JobDetail;
  NotificationSettingsView?: NotificationSettingsView;
  PipelineView?: PipelineView;
  PreferenceUpdateResult?: PreferenceUpdateResult;
  ProfileView?: ProfileView;
  ResumeImportResult?: ResumeImportResult;
  SearchJobsParams?: SearchJobsParams;
  SearchResults?: SearchResults;
  SourceImportResult?: SourceImportResult;
  SourceRemovalResult?: SourceRemovalResult;
  TasteAction?: TasteAction;
  TasteProfileView?: TasteProfileView;
  TasteUpdateResult?: TasteUpdateResult;
  TasteView?: TasteView;
  TokenList?: TokenList;
  UpdateNotificationsRequest?: UpdateNotificationsRequest;
  UpdatePreferencesParams?: UpdatePreferencesParams;
  VerificationReport?: VerificationReport;
}
/**
 * `GET /api/v1/account`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "AccountView".
 */
export interface AccountView {
  /**
   * How this request authenticated: `oidc`, `token` or `dev`.
   */
  authenticated_with: string;
  cloud: CloudStateView;
  created_at: string;
  /**
   * `usr_…`: the internal account id.
   */
  id: string;
  identities: IdentityView[];
}
/**
 * Where the account's data stands in the cloud.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "CloudStateView".
 */
export interface CloudStateView {
  /**
   * Changes recorded so far (the sync cursor's upper bound).
   */
  change_seq: number;
  /**
   * Feedback events (not counting "seen" marks).
   */
  feedback: number;
  last_shortlist_at?: string | null;
  last_sync_at?: string | null;
  /**
   * For notifications (BRU-295): the last recommendation change covered.
   */
  notification_cursor: number;
  profile_revision: number;
}
/**
 * One identity-provider identity linked to the account.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "IdentityView".
 */
export interface IdentityView {
  created_at: string;
  issuer: string;
  last_login_at: string;
}
/**
 * The answer of `prepare_application_context`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ApplicationContext".
 */
export interface ApplicationContext {
  /**
   * What to be careful about: the brief's caveats and unknowns,
   * eligibility conditions, verification state.
   */
  caveats: string[];
  /**
   * Only when requested.
   */
  contact?: ContactDetails | null;
  decision?: DecisionView | null;
  eligibility: EligibilityBrief;
  /**
   * Usable facts about the person as a whole (skills lists,
   * certifications) that bear on the job.
   */
  general: Fact[];
  headline?: string | null;
  job: ContextJob;
  job_asks: JobAsks;
  /**
   * Where the person lives, as they wrote it.
   */
  location?: string | null;
  /**
   * What the job asks for that no usable evidence covers.
   */
  missing_evidence: string[];
  /**
   * How to use this context.
   */
  policy: string;
  /**
   * Most relevant first.
   */
  relevant_experience: EvidenceGroup[];
  relevant_projects: EvidenceGroup[];
  verification: VerificationBrief;
  withheld: Withheld;
}
/**
 * Contact details, included only when explicitly requested.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ContactDetails".
 */
export interface ContactDetails {
  contacts: ContactView[];
  name?: string | null;
}
/**
 * One way to reach the person.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ContactView".
 */
export interface ContactView {
  /**
   * `email`, `phone`, `linkedin`, `github` or `website`.
   */
  kind: string;
  value: string;
}
/**
 * The decision brief: what someone needs to decide whether a job is
 * worth their time.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DecisionView".
 */
export interface DecisionView {
  /**
   * What goes against the fit, most material first (why a job that
   * looks relevant is held back).
   */
  against?: string[];
  /**
   * What counts against it, and conditions.
   */
  caveats: string[];
  /**
   * Useful practical facts (pay reaching the person's target). Never
   * reasons for fit.
   */
  facts?: string[];
  /**
   * How well it fits what they want: `strong`, `plausible`,
   * `insufficient` or `poor`.
   */
  fit?: string | null;
  /**
   * The person's history with it.
   */
  history: string[];
  recommendation: Recommendation;
  /**
   * Why it is not recommended, or what to check first, when it applies.
   */
  recommendation_note?: string | null;
  /**
   * Role · level · stack · domain · pay · where.
   */
  summary: string;
  tier: FitTier;
  /**
   * What the posting doesn't say that matters to the person: the
   * things to check.
   */
  unknowns: string[];
  /**
   * One sentence.
   */
  verdict: string;
  /**
   * Why it may be worth the person's time, strongest first.
   */
  worth: string[];
}
/**
 * Eligibility at a glance.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EligibilityBrief".
 */
export interface EligibilityBrief {
  /**
   * One line: why.
   */
  headline: string;
  status: EligibilityStatus;
}
/**
 * One usable fact about the person.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Fact".
 */
export interface Fact {
  /**
   * `clm_…`.
   */
  claim_id: string;
  /**
   * `employment`, `responsibility`, `accomplishment`, `technology`,
   * `domain`, `role`, `ownership`, `project`, `skill`, `education`, `other`.
   */
  kind: string;
  source?: FactSource | null;
  /**
   * The claim, as written (the resume's words, or the person's).
   */
  text: string;
  /**
   * Normalized topic for technology, domain and role facts.
   */
  topic?: string | null;
  usable_because: UsableBasis;
}
/**
 * Where a fact comes from.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FactSource".
 */
export interface FactSource {
  /**
   * `doc_…` of the resume.
   */
  document: string;
  section?: string | null;
  /**
   * The resume's own words.
   */
  snippet: string;
}
/**
 * The job, briefly.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ContextJob".
 */
export interface ContextJob {
  apply_url?: string | null;
  company: string;
  compensation: CompensationView;
  /**
   * The start of the posting's description, verbatim.
   */
  description_excerpt: string;
  employment?: string | null;
  /**
   * `opp_…`.
   */
  id: string;
  locations: string[];
  title: string;
  url: string;
  workplace?: string | null;
}
/**
 * Published pay, as facts.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "CompensationView".
 */
export interface CompensationView {
  /**
   * Each published range in words ("USD 140,000 – 180,000 per year").
   * A range whose currency is only an ambiguous symbol says so; it is
   * never read as a low number.
   */
  ranges: string[];
  /**
   * `published`, `not_published` or `not_observed`.
   */
  status: string;
  /**
   * The source's own summary text, verbatim.
   */
  summary?: string | null;
  /**
   * Whether the facts come from a verification (`true`) or from
   * discovery (`false`).
   */
  verified: boolean;
  verified_at?: string | null;
}
/**
 * What the job asks for, as read from the posting.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "JobAsks".
 */
export interface JobAsks {
  domains: string[];
  level?: string | null;
  roles: string[];
  technologies: TechnologyMatch[];
}
/**
 * A technology the job names, and the person's usable evidence for it.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TechnologyMatch".
 */
export interface TechnologyMatch {
  /**
   * Usable evidence (empty when there is none).
   */
  evidence: Fact[];
  /**
   * `required`, `preferred` or `mentioned`, as the posting says.
   */
  job_requirement: string;
  name: string;
}
/**
 * An experience or project, with its usable facts.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EvidenceGroup".
 */
export interface EvidenceGroup {
  facts: Fact[];
  /**
   * `exp_…` or `proj_…`.
   */
  id: string;
  /**
   * "Senior Engineer at Acme", or the project name.
   */
  label: string;
  period?: string | null;
  /**
   * What connects it to this job ("uses PostgreSQL, which the job
   * requires").
   */
  relevance: string[];
}
/**
 * Verification at a glance.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "VerificationBrief".
 */
export interface VerificationBrief {
  /**
   * Who publishes the listing the state rests on
   * (`employer_configured_ats`, `employer_first_party`, …).
   */
  authority?: string | null;
  freshness?: Freshness | null;
  /**
   * Why it is not trusted, when it isn't.
   */
  not_trusted_because?: string | null;
  /**
   * The source the state rests on (`greenhouse:stripe`).
   */
  source?: string | null;
  state: VerificationState;
  /**
   * Recent enough, from an authoritative source, to recommend on.
   */
  trusted: boolean;
  /**
   * When the last successful verification happened (RFC 3339).
   */
  verified_at?: string | null;
}
/**
 * Claims left out, by why. Their text is never included.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Withheld".
 */
export interface Withheld {
  /**
   * How the person can review them.
   */
  how_to_review: string;
  /**
   * Inferred, uncertain, or no longer in the resume: usable once the
   * person confirms them.
   */
  needs_review: number;
  /**
   * Rejected by the person: never used.
   */
  rejected: number;
}
/**
 * `GET /api/v1/auth/config`: how to sign in (public).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "AuthConfigView".
 */
export interface AuthConfigView {
  /**
   * The audience to request tokens for.
   */
  audience?: string | null;
  /**
   * The request parameter that carries it (`resource`, RFC 8707, or
   * `audience`); absent means none is sent.
   */
  audience_parameter?: string | null;
  /**
   * The public client the CLI signs in with (device authorization).
   */
  cli_client_id?: string | null;
  device_authorization_endpoint?: string | null;
  /**
   * The identity provider (OIDC issuer URL), when `oidc`.
   */
  issuer?: string | null;
  /**
   * `oidc` or `dev`.
   */
  mode: string;
  revocation_endpoint?: string | null;
  scopes?: string | null;
  token_endpoint?: string | null;
}
/**
 * The answer of a claim decision.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ClaimDecisionResult".
 */
export interface ClaimDecisionResult {
  decided: DecidedClaim[];
  /**
   * Claims still waiting for review.
   */
  needs_review_total: number;
}
/**
 * One claim after a decision.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DecidedClaim".
 */
export interface DecidedClaim {
  id: string;
  /**
   * `confirmed`, `rejected`, `extracted`, `inferred`, …
   */
  state: string;
  text: string;
  /**
   * Whether it may now be used as evidence.
   */
  usable: boolean;
}
/**
 * The claims waiting for the person's decision, with the words behind
 * each.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ClaimReview".
 */
export interface ClaimReview {
  claims: UnresolvedClaim[];
  total: number;
}
/**
 * A claim waiting for the person's decision. Not usable as a fact until
 * confirmed.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "UnresolvedClaim".
 */
export interface UnresolvedClaim {
  /**
   * What it is about ("Senior Engineer at Acme", a project's name);
   * absent for the profile in general.
   */
  about?: string | null;
  /**
   * `exp_…`, `proj_…` or `edu_…` it is about.
   */
  about_id?: string | null;
  /**
   * For inferred claims: what the inference rests on.
   */
  basis?: string | null;
  /**
   * How sure the reading is: `high`, `medium` or `low`.
   */
  confidence?: string;
  /**
   * The file (or account) the words are from.
   */
  document?: string | null;
  /**
   * Every source that says it, its main one first (a resume and a
   * LinkedIn export both listing a position): the detail behind
   * `snippet`.
   */
  evidence?: EvidenceView[];
  /**
   * `clm_…` (confirm with `narrow claims confirm <id>`).
   */
  id: string;
  kind: string;
  /**
   * `extracted` (read from a source), `inferred` (concluded by JobHunt)
   * or `user_entered`.
   */
  provenance?: string;
  /**
   * The section the words are from.
   */
  section?: string | null;
  /**
   * The source's own words behind it, verbatim (its main source).
   */
  snippet?: string | null;
  text: string;
  /**
   * Why it needs review.
   */
  why: string;
}
/**
 * One source's words behind a claim.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EvidenceView".
 */
export interface EvidenceView {
  /**
   * The file or account (`resume.pdf`, `github.com/octocat`).
   */
  document?: string | null;
  /**
   * Where in the source ("Experience", "Positions", "Repositories").
   */
  section?: string | null;
  /**
   * The source's own words, verbatim (empty when the source gave none).
   */
  snippet: string;
  /**
   * `resume`, `linkedin` or `github`.
   */
  source: string;
}
/**
 * `POST /api/v1/notifications/confirm`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ConfirmEmailRequest".
 */
export interface ConfirmEmailRequest {
  /**
   * The token from the confirmation link.
   */
  token: string;
}
/**
 * `POST /api/v1/tokens`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "CreateTokenRequest".
 */
export interface CreateTokenRequest {
  /**
   * Days until it expires (default 90, at most 365).
   */
  expires_in_days?: number | null;
  /**
   * What the token is for ("Claude Desktop").
   */
  name: string;
}
/**
 * A token just created: the only time its secret is shown.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "CreatedToken".
 */
export interface CreatedToken {
  /**
   * `jh_pat_…`: send it as `Authorization: Bearer <secret>`.
   */
  secret: string;
  token: TokenView;
}
/**
 * A personal access token (never its secret).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TokenView".
 */
export interface TokenView {
  created_at: string;
  expires_at?: string | null;
  /**
   * `tok_…`.
   */
  id: string;
  last_used_at?: string | null;
  name: string;
  revoked_at?: string | null;
}
/**
 * `POST /api/v1/profile/claims`: confirm, reject or reset claims.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DecideClaimsRequest".
 */
export interface DecideClaimsRequest {
  decision: ClaimDecision;
  /**
   * `clm_…` ids.
   */
  ids: string[];
  /**
   * Why (kept on the claims verbatim).
   */
  note?: string | null;
}
/**
 * A token issued by a development server.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DevTokenResponse".
 */
export interface DevTokenResponse {
  access_token: string;
  expires_in: number;
}
/**
 * Every error: `{"error": {"code", "message", "hint", "request_id"}}`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  error: ErrorDetail;
}
/**
 * An error, with a stable `code` (the same codes as the CLI and the MCP
 * tools: `unknown_opportunity`, `no_profile`, `conflict`, …, plus
 * `unauthenticated`, `forbidden`, `not_found`, `invalid_request`).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ErrorDetail".
 */
export interface ErrorDetail {
  code: string;
  hint?: string | null;
  message: string;
}
/**
 * The answer of `get_feed` (and `GET /api/v1/feed`).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedView".
 */
export interface FeedView {
  /**
   * Nothing new is worth the person's time right now.
   */
  caught_up: boolean;
  discovery: DiscoveryStatus;
  generated_at: string;
  /**
   * Best first. Few on purpose; empty when there is nothing new worth
   * the person's time.
   */
  items: FeedItem[];
  learning: Learning;
  notes?: string[];
  /**
   * Recommendations shown earlier that the person let pass (not shown
   * again unless they change).
   */
  passed_over: number;
  pipeline: PipelineCounts;
  refresh: RefreshSummary;
  summary: FeedSummary;
  /**
   * Listings verified while preparing the feed.
   */
  verified_now: number;
}
/**
 * Where background discovery stands.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DiscoveryStatus".
 */
export interface DiscoveryStatus {
  /**
   * When a job board was last read.
   */
  last_read_at?: string | null;
  /**
   * `background` (JobHunt Cloud reads job boards on a schedule) or
   * `on_demand` (searches read them when stale).
   */
  mode: string;
  /**
   * When the next scheduled read is due (background only).
   */
  next_read_at?: string | null;
}
/**
 * One item on the feed: a shortlist item, with why it is on the feed.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedItem".
 */
export interface FeedItem {
  /**
   * Other recommendations at the same company, held off the feed so
   * that one company doesn't fill it (best first).
   */
  also_at_company?: SameCompany[];
  /**
   * What changed, for `changed` items.
   */
  changes?: string[];
  company: string;
  compensation: CompensationView1;
  /**
   * What to consider: caveats, then unknowns (up to 3).
   */
  consider: string[];
  department?: string | null;
  eligibility: EligibilityBrief;
  /**
   * Useful practical facts (pay reaching the person's target, remote
   * from where they want). Never reasons for fit.
   */
  facts?: string[];
  /**
   * When a feed or shortlist first showed it to the person.
   */
  first_shown_at?: string | null;
  /**
   * How well it fits what the person wants: `strong`, `plausible`,
   * `insufficient` or `poor` (the tier, in fit's words).
   */
  fit?: string | null;
  /**
   * `opp_…`: the logical opportunity (one job, however many sources
   * list it). Use it with every other tool.
   */
  id: string;
  /**
   * Every location the listing names, primary first.
   */
  locations?: string[];
  /**
   * The suggested next step, as a CLI command.
   */
  next_step: string;
  /**
   * `new`, or `changed` (reviewed before, changed materially since).
   */
  reason: "new" | "changed";
  recommendation: Recommendation;
  /**
   * What to check first, when it applies.
   */
  recommendation_note?: string | null;
  remote?: boolean | null;
  /**
   * Shown by the CLI (`opp_1a2b3c4d`); accepted back while unique.
   */
  short_id: string;
  /**
   * How many sources list it.
   */
  sources: number;
  /**
   * Where it is in the person's pipeline (`unseen`, `seen`, `saved`).
   */
  stage: "unseen" | "seen" | "saved" | "rejected" | "applied" | "interviewing" | "offer";
  /**
   * Role · level · stack · domain · pay · where.
   */
  summary: string;
  team?: string | null;
  tier: FitTier;
  title: string;
  /**
   * Things to check before spending time on it (pay not published,
   * remote scope unclear, travel expected): the person's own
   * requirements first, up to 3.
   */
  to_check?: string[];
  /**
   * The lines of `consider` about what the posting doesn't say
   * (unknowns, not cautions); the others are caveats.
   */
  unknowns?: string[];
  verification: VerificationBrief;
  /**
   * Why it may be worth the person's time (up to 4; verification and
   * eligibility are in their own fields).
   */
  why: string[];
  /**
   * `remote`, `hybrid` or `onsite`, as the listing says.
   */
  workplace?: string | null;
}
/**
 * Another recommendation at the same company as a feed item, not on the
 * feed itself (and not recorded as shown).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SameCompany".
 */
export interface SameCompany {
  /**
   * `opp_…`.
   */
  id: string;
  title: string;
}
/**
 * Published pay, as facts.
 */
export interface CompensationView1 {
  /**
   * Each published range in words ("USD 140,000 – 180,000 per year").
   * A range whose currency is only an ambiguous symbol says so; it is
   * never read as a low number.
   */
  ranges: string[];
  /**
   * `published`, `not_published` or `not_observed`.
   */
  status: string;
  /**
   * The source's own summary text, verbatim.
   */
  summary?: string | null;
  /**
   * Whether the facts come from a verification (`true`) or from
   * discovery (`false`).
   */
  verified: boolean;
  verified_at?: string | null;
}
/**
 * What feedback has taught so far.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Learning".
 */
export interface Learning {
  /**
   * Patterns learned from it that affect ranking now.
   */
  active_patterns: number;
  /**
   * Pieces of feedback (not counting "looked at").
   */
  feedback: number;
  /**
   * The person has stated preferences (they always outrank learned
   * taste).
   */
  has_preferences: boolean;
}
/**
 * Opportunities in the person's pipeline, by stage.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PipelineCounts".
 */
export interface PipelineCounts {
  applied: number;
  interviewing: number;
  offer: number;
  saved: number;
}
/**
 * How discovery was (or wasn't) refreshed for a search.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "RefreshSummary".
 */
export interface RefreshSummary {
  closed_jobs?: number | null;
  new_jobs?: number | null;
  /**
   * Sources were read during this search.
   */
  performed: boolean;
  /**
   * Why ("sources last read 2 days ago", "every source read 3 hours ago").
   */
  reason: string;
  sources_failed?: number | null;
  sources_read?: number | null;
  updated_jobs?: number | null;
  /**
   * Problems that did not stop the refresh.
   */
  warnings?: string[];
}
/**
 * From every open job to what is on the feed. Every number is counted,
 * none estimated.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedSummary".
 */
export interface FeedSummary {
  /**
   * Reviewed before and changed materially since.
   */
  changed: number;
  /**
   * Open opportunities checked.
   */
  checked: number;
  /**
   * Of those, new to the person.
   */
  new: number;
  /**
   * Left after eligibility, closed listings, pay minimums and what the
   * person already decided (rejected, applied).
   */
  passed_eligibility: number;
  /**
   * On the feed now.
   */
  shown: number;
  /**
   * Of those, strong fits: what Today chooses from.
   */
  strong_fits?: number;
  /**
   * Of those, strong fits and jobs worth reviewing.
   */
  worth_reviewing: number;
}
/**
 * `POST /api/v1/opportunities/{id}/feedback`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedbackRequest".
 */
export interface FeedbackRequest {
  action: FeedbackInput;
  /**
   * Why, in the person's own words. Stored verbatim (encrypted).
   */
  reason?: string | null;
}
/**
 * The answer of `save_job`, `reject_job`, `mark_applied` and
 * `record_feedback`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedbackResult".
 */
export interface FeedbackResult {
  /**
   * `save`, `reject`, `applied`, …
   */
  action: string;
  company: string;
  /**
   * `fb_…` of the stored event (or the earlier one this repeats).
   */
  feedback_id?: string | null;
  /**
   * `opp_…`.
   */
  id: string;
  interpretation?: ReasonInterpretation | null;
  /**
   * Patterns that now affect ranking.
   */
  learned?: string[];
  note?: string | null;
  previous: PipelineStateView;
  /**
   * Whether a new feedback event was stored. `false` means the request
   * repeated one already in effect (same action, same reason): nothing
   * changed, and retrying is safe.
   */
  recorded: boolean;
  state: PipelineStateView1;
  /**
   * Whether what JobHunt learned from feedback changed.
   */
  taste_changed: boolean;
  title: string;
  /**
   * Patterns that no longer do.
   */
  unlearned?: string[];
}
/**
 * How a reason was read.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ReasonInterpretation".
 */
export interface ReasonInterpretation {
  /**
   * What was recognized ("avoid company: large companies").
   */
  read_as: string[];
  /**
   * Which reader read it (`rules/1`).
   */
  reader: string;
  /**
   * The reason, verbatim (it is always kept as written).
   */
  reason: string;
  /**
   * Something in it was recognized.
   */
  understood: boolean;
}
/**
 * The state before this request.
 */
export interface PipelineStateView {
  /**
   * Every action other than looking at it, oldest first.
   */
  feedback: FeedbackView[];
  /**
   * The furthest application stage reached (kept after withdrawing).
   */
  furthest: "unseen" | "seen" | "saved" | "rejected" | "applied" | "interviewing" | "offer";
  sentiment?: SentimentView | null;
  /**
   * When the current stage was reached.
   */
  since?: string | null;
  stage: PipelineStage;
}
/**
 * A past action, verbatim.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "FeedbackView".
 */
export interface FeedbackView {
  /**
   * `save`, `reject`, `applied`, `like`, …
   */
  action: string;
  at: string;
  /**
   * `fb_…`.
   */
  id: string;
  /**
   * The person's words, exactly as given.
   */
  reason?: string | null;
}
/**
 * The state now.
 */
export interface PipelineStateView1 {
  /**
   * Every action other than looking at it, oldest first.
   */
  feedback: FeedbackView[];
  /**
   * The furthest application stage reached (kept after withdrawing).
   */
  furthest: "unseen" | "seen" | "saved" | "rejected" | "applied" | "interviewing" | "offer";
  sentiment?: SentimentView | null;
  /**
   * When the current stage was reached.
   */
  since?: string | null;
  stage: PipelineStage;
}
/**
 * `POST /api/v1/profile/github`: import a public GitHub account.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "GithubImportRequest".
 */
export interface GithubImportRequest {
  /**
   * A GitHub username or profile URL. Defaults to the account imported
   * before, or the GitHub link on the profile.
   */
  username?: string | null;
}
/**
 * The answer of `get_job`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "JobDetail".
 */
export interface JobDetail {
  apply_url?: string | null;
  company: string;
  compensation: CompensationView;
  /**
   * The decision brief (`None` without a profile).
   */
  decision?: DecisionView | null;
  department?: string | null;
  /**
   * The description as text: the first part, unless the full text was
   * requested.
   */
  description: string;
  description_truncated: boolean;
  /**
   * Eligibility with its reasons (`None` without a profile).
   */
  eligibility?: EligibilityDetail | null;
  employment?: string | null;
  /**
   * `opp_…`: the logical opportunity.
   */
  id: string;
  /**
   * `job_…` of the record the details are read from.
   */
  job_id: string;
  /**
   * Every location the source lists, primary first.
   */
  locations: string[];
  pipeline: PipelineStateView2;
  posted_at?: string | null;
  remote?: boolean | null;
  short_id: string;
  /**
   * How many sources list it.
   */
  source_count: number;
  /**
   * Every source record (provenance and per-source verification), when
   * requested.
   */
  sources?: SourceRecordView[] | null;
  team?: string | null;
  title: string;
  url: string;
  verification: VerificationBrief;
  workplace?: string | null;
}
/**
 * An eligibility decision with its reasons.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EligibilityDetail".
 */
export interface EligibilityDetail {
  /**
   * Contradictions between statements, kept visible.
   */
  conflicts?: string[];
  /**
   * A compatibility signal, not legal advice about work authorization.
   */
  disclaimer: string;
  headline: string;
  /**
   * The way of doing the job the status is about ("Remote (Americas)").
   */
  option?: string | null;
  reasons: EligibilityReason[];
  status: EligibilityStatus;
}
/**
 * One step of an eligibility decision.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EligibilityReason".
 */
export interface EligibilityReason {
  conclusion: string;
  /**
   * The posting's own words behind it.
   */
  evidence?: string[];
  /**
   * The rule (`country_constraint`, `authorization`, `timezone`, …).
   */
  rule: string;
  /**
   * `pass`, `conditional`, `unknown`, `fail` or `not_applicable`.
   */
  verdict: string;
}
/**
 * The person's state on an opportunity, folded from their feedback.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PipelineStateView".
 */
export interface PipelineStateView2 {
  /**
   * Every action other than looking at it, oldest first.
   */
  feedback: FeedbackView[];
  /**
   * The furthest application stage reached (kept after withdrawing).
   */
  furthest: "unseen" | "seen" | "saved" | "rejected" | "applied" | "interviewing" | "offer";
  sentiment?: SentimentView | null;
  /**
   * When the current stage was reached.
   */
  since?: string | null;
  stage: PipelineStage;
}
/**
 * One source record of an opportunity (provenance).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SourceRecordView".
 */
export interface SourceRecordView {
  authority: string;
  closed_at?: string | null;
  first_seen_at: string;
  /**
   * `job_…`: this source's record.
   */
  job_id: string;
  last_attempt?: AttemptView | null;
  last_seen_at: string;
  last_success_at?: string | null;
  /**
   * `greenhouse:stripe`.
   */
  source: string;
  source_record_id?: string | null;
  /**
   * `open` or `closed` (as discovery last saw it).
   */
  status: string;
  url: string;
  verification: VerificationState;
}
/**
 * One verification attempt of one source record.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "AttemptView".
 */
export interface AttemptView {
  application: ApplicationState;
  /**
   * `probed`, `published`, `listing_page` or `not_checked`.
   */
  application_basis: string;
  application_url?: string | null;
  at: string;
  authority: string;
  checked_url?: string | null;
  /**
   * Why it could not reach an answer, when it couldn't.
   */
  failure?: string | null;
  listing: ListingState;
  /**
   * How it was checked (`greenhouse_job_api`, `ashby_board_api`, …).
   */
  method: string;
  /**
   * What this attempt could not establish.
   */
  unknowns?: string[];
}
/**
 * `GET /api/v1/notifications`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "NotificationSettingsView".
 */
export interface NotificationSettingsView {
  /**
   * Whether this service can send email at all.
   */
  available: boolean;
  /**
   * `immediate` (soon after a strong match appears, at most one email
   * every few hours) or `daily` (at most one a day).
   */
  cadence: string;
  confirmation_sent_at?: string | null;
  email?: string | null;
  /**
   * Emails about strong new matches are on.
   */
  email_enabled: boolean;
  /**
   * `none`, `unconfirmed` (a link was sent; nothing else is sent until
   * it is followed) or `confirmed`.
   */
  email_status: string;
  /**
   * Opportunities in one email at most.
   */
  max_items: number;
  /**
   * Hours between emails at most, with the `immediate` cadence.
   */
  min_interval_hours: number;
  /**
   * The latest emails, newest first.
   */
  recent: DeliveryView[];
}
/**
 * One notification email, for the settings page (never its content).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DeliveryView".
 */
export interface DeliveryView {
  created_at: string;
  id: string;
  /**
   * `recommendations` or `confirmation`.
   */
  kind: string;
  /**
   * Opportunities in it.
   */
  opportunities: number;
  sent_at?: string | null;
  /**
   * `pending`, `sent`, `failed` or `abandoned`.
   */
  status: string;
}
/**
 * The answer of `get_pipeline`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PipelineView".
 */
export interface PipelineView {
  /**
   * Offers first, then interviewing, applied, saved (and rejected, when
   * asked for); latest first within a stage.
   */
  entries: PipelineEntryView[];
}
/**
 * One opportunity in the pipeline.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PipelineEntryView".
 */
export interface PipelineEntryView {
  company: string;
  /**
   * `opp_…`.
   */
  id: string;
  /**
   * The latest reason the person gave, verbatim.
   */
  last_reason?: string | null;
  /**
   * Every source record of it is closed.
   */
  listing_closed: boolean;
  sentiment?: SentimentView | null;
  short_id: string;
  /**
   * When the current stage was reached.
   */
  since?: string | null;
  stage: PipelineStage;
  title: string;
}
/**
 * The answer of `update_preferences`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PreferenceUpdateResult".
 */
export interface PreferenceUpdateResult {
  /**
   * Every preference in effect now.
   */
  active: PreferenceView[];
  /**
   * What was understood, from the statement and structured values.
   */
  interpreted: PreferenceView[];
  /**
   * Parts of the statement that were not understood, verbatim.
   */
  not_understood: string[];
  /**
   * Ids removed (or, for a resume-derived record, rejected).
   */
  removed: string[];
  /**
   * Earlier preferences these replaced.
   */
  replaced: PreferenceView[];
  /**
   * The statement, as stored.
   */
  statement?: StatementView | null;
  /**
   * The interpretations JobHunt is unsure about (also in
   * `interpreted`), for the person to confirm or correct.
   */
  uncertain: PreferenceView[];
  /**
   * Everything asked was already in effect; nothing changed.
   */
  unchanged: boolean;
}
/**
 * One preference.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PreferenceView".
 */
export interface PreferenceView {
  active: boolean;
  /**
   * `role`, `compensation`, `location`, `company`, `domain`, `work_style`.
   */
  category: string;
  /**
   * `certain`, or `uncertain` when JobHunt read it with doubts.
   */
  certainty: string;
  /**
   * What the person must settle before Narrow relies on it (read from
   * their words, and ambiguous in a way that matters). Until then it is
   * unresolved.
   */
  clarify?: Clarify | null;
  /**
   * `pref_…`.
   */
  id: string;
  /**
   * `requirement` (a stated conflict can leave a job out; unknown stays
   * unresolved) or `preference` (ranking only). See [`layer`].
   */
  layer: string;
  /**
   * How an ambiguous part was read, for the person to check.
   */
  note?: string | null;
  /**
   * `statement` (read from the person's words) or `user_entered`.
   */
  origin: string;
  /**
   * The words it was read from, verbatim.
   */
  snippet?: string | null;
  /**
   * `required`, `wanted`, `acceptable` or `unwanted`.
   */
  stance: string;
  /**
   * `stmt_…` it was read from.
   */
  statement_id?: string | null;
  /**
   * The value, readable ("backend roles", "at least USD 120,000 per year").
   */
  value: string;
}
/**
 * A statement in the person's words.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "StatementView".
 */
export interface StatementView {
  at: string;
  /**
   * `stmt_…`.
   */
  id: string;
  /**
   * Parts of the text that produced no preference (kept, never dropped).
   */
  not_understood: string[];
  /**
   * `understood`, `partial` or `not_understood`.
   */
  reading: string;
  /**
   * Verbatim.
   */
  text: string;
}
/**
 * The answer of `get_profile`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ProfileView".
 */
export interface ProfileView {
  /**
   * Always true: names and contact details are not part of this view.
   */
  contact_details_omitted: boolean;
  /**
   * Imported sources (resumes, a LinkedIn export, a GitHub account),
   * the current ones first.
   */
  documents?: DocumentSummary[];
  domains: Signal[];
  education?: EducationSummary[];
  experiences: ExperienceSummary[];
  /**
   * What is missing or uncertain.
   */
  gaps: string[];
  headline?: string | null;
  /**
   * Where the person lives, as they wrote it (eligibility depends on it).
   */
  location?: string | null;
  /**
   * Claims needing the person's review (the first few).
   */
  needs_review: UnresolvedClaim[];
  needs_review_total: number;
  /**
   * Seniority and ownership signals (led, mentored, founding).
   */
  ownership_signals: Signal[];
  /**
   * Preferences in effect.
   */
  preferences: PreferenceView[];
  projects?: ProjectSummary[];
  /**
   * Kinds of engineering role the experience shows (backend, platform).
   */
  role_signals: Signal[];
  /**
   * What the person said, verbatim.
   */
  statements: StatementView[];
  summary?: string | null;
  /**
   * Strongest evidence first.
   */
  technologies: TechnologyEvidence[];
}
/**
 * A source imported into the profile (never its text): a resume, a
 * LinkedIn export, a GitHub account.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "DocumentSummary".
 */
export interface DocumentSummary {
  /**
   * The most recently imported of its source: the resume (or export,
   * or account) the profile follows.
   */
  current: boolean;
  file_name?: string | null;
  first_imported_at: string;
  /**
   * `doc_…`.
   */
  id: string;
  /**
   * `pdf`, `text` or `markdown` (a resume), `linkedin` or `github`.
   */
  kind: string;
  last_imported_at: string;
  pages?: number | null;
  /**
   * `resume`, `linkedin` or `github`.
   */
  source?: string;
}
/**
 * A domain or role kind and how much evidence backs it.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Signal".
 */
export interface Signal {
  evidence: number;
  name: string;
}
/**
 * An education entry.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "EducationSummary".
 */
export interface EducationSummary {
  degree?: string | null;
  field?: string | null;
  /**
   * `edu_…`.
   */
  id: string;
  institution: string;
  period?: string | null;
  /**
   * `resume`, `linkedin`, `github`: the sources that contain it now.
   */
  sources?: string[];
  stale: boolean;
}
/**
 * One experience.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ExperienceSummary".
 */
export interface ExperienceSummary {
  company?: string | null;
  current: boolean;
  /**
   * Domains worked in there.
   */
  domains: string[];
  /**
   * `exp_…`.
   */
  id: string;
  /**
   * "Mar 2021 – Present".
   */
  period?: string | null;
  /**
   * The sources that contain it now: `resume`, `linkedin`, `github`
   * (empty for what the person entered themselves, or when stale).
   */
  sources?: string[];
  /**
   * No source contains it any more.
   */
  stale: boolean;
  /**
   * Technologies used there (evidence that is not rejected).
   */
  technologies: string[];
  title?: string | null;
}
/**
 * A project.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ProjectSummary".
 */
export interface ProjectSummary {
  description?: string | null;
  /**
   * `proj_…`.
   */
  id: string;
  name: string;
  period?: string | null;
  role?: string | null;
  /**
   * `resume`, `linkedin`, `github`: the sources that contain it now.
   */
  sources?: string[];
  stale: boolean;
  technologies: string[];
  /**
   * Its address (a repository), when a source gave one.
   */
  url?: string | null;
}
/**
 * A technology or skill and what backs it.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TechnologyEvidence".
 */
export interface TechnologyEvidence {
  /**
   * Claims backing it (not rejected).
   */
  evidence: number;
  /**
   * `current`, or the last year it was used ("2023").
   */
  last_used?: string | null;
  name: string;
  /**
   * `demonstrated` (used in an experience or project), `user_stated`,
   * `listed` (only in a skills list) or `unsupported`.
   */
  strength: string;
  /**
   * Where it was used ("Senior Engineer at Acme").
   */
  used_at: string[];
}
/**
 * What importing a resume changed.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ResumeImportResult".
 */
export interface ResumeImportResult {
  claims: TallyView;
  education: TallyView;
  experiences: TallyView;
  file_name?: string | null;
  /**
   * The profile had no resume before.
   */
  first_import: boolean;
  /**
   * Lines of the resume that were not understood.
   */
  ignored_lines: number;
  /**
   * Confirmed claims found again (still confirmed).
   */
  kept_confirmed: number;
  /**
   * Rejected claims found again (still rejected).
   */
  kept_rejected: number;
  /**
   * Claims now waiting for the person's review.
   */
  needs_review: number;
  /**
   * Doubts about particular records ("Freelance: no dates found").
   */
  notes: string[];
  pages?: number | null;
  /**
   * Records where the person's own edits were kept over the resume.
   */
  preserved_edits: number;
  profile: ProfileView1;
  projects: TallyView;
  /**
   * Confirmed claims whose wording changed: they need confirming again.
   */
  reconfirm: number;
  /**
   * This exact file was imported before (nothing new to read).
   */
  same_file: boolean;
  skills: TallyView;
  /**
   * Confirmed claims whose source left the resume.
   */
  stale_confirmed: number;
}
/**
 * Counts of one kind of record in an import.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TallyView".
 */
export interface TallyView {
  added: number;
  /**
   * Already in the profile from another source (or entered by the
   * person): this source was added as evidence, not as a duplicate.
   */
  corroborated?: number;
  /**
   * Back in the resume after being stale.
   */
  restored: number;
  /**
   * No longer in the resume (kept, marked stale).
   */
  stale: number;
  unchanged: number;
  updated: number;
}
/**
 * The profile after the import.
 */
export interface ProfileView1 {
  /**
   * Always true: names and contact details are not part of this view.
   */
  contact_details_omitted: boolean;
  /**
   * Imported sources (resumes, a LinkedIn export, a GitHub account),
   * the current ones first.
   */
  documents?: DocumentSummary[];
  domains: Signal[];
  education?: EducationSummary[];
  experiences: ExperienceSummary[];
  /**
   * What is missing or uncertain.
   */
  gaps: string[];
  headline?: string | null;
  /**
   * Where the person lives, as they wrote it (eligibility depends on it).
   */
  location?: string | null;
  /**
   * Claims needing the person's review (the first few).
   */
  needs_review: UnresolvedClaim[];
  needs_review_total: number;
  /**
   * Seniority and ownership signals (led, mentored, founding).
   */
  ownership_signals: Signal[];
  /**
   * Preferences in effect.
   */
  preferences: PreferenceView[];
  projects?: ProjectSummary[];
  /**
   * Kinds of engineering role the experience shows (backend, platform).
   */
  role_signals: Signal[];
  /**
   * What the person said, verbatim.
   */
  statements: StatementView[];
  summary?: string | null;
  /**
   * Strongest evidence first.
   */
  technologies: TechnologyEvidence[];
}
/**
 * Arguments of `search_jobs`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SearchJobsParams".
 */
export interface SearchJobsParams {
  /**
   * Also return opportunities ranked maybe or low priority (default
   * false).
   */
  include_lower_tiers?: boolean;
  /**
   * How many opportunities to return, 1 to 25. Default 5: the short
   * list is meant to be short.
   */
  limit?: number | null;
  /**
   * Words every job must contain (in its title, company, location,
   * department or team), e.g. "rust backend". Omit to search everything.
   */
  query?: string | null;
  /**
   * Whether to read job boards first. Default "auto".
   */
  refresh?: "auto" | "always" | "never";
  /**
   * Verify the best candidates at their employers' sources when their
   * last verification isn't recent (default true; ignored with refresh
   * "never").
   */
  verify?: boolean | null;
}
/**
 * The answer of `search_jobs` (and `narrow find --json`).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SearchResults".
 */
export interface SearchResults {
  funnel: Funnel;
  learning: Learning;
  not_shown: NotShown;
  /**
   * Things worth knowing about these results.
   */
  notes?: string[];
  query?: string | null;
  refresh: RefreshSummary;
  /**
   * Best first. Small on purpose.
   */
  results: ShortlistItem[];
  /**
   * Listings verified during this search.
   */
  verified_now: number;
}
/**
 * From every open opportunity to the few shown.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "Funnel".
 */
export interface Funnel {
  /**
   * Open opportunities checked (matching the query, if any).
   */
  checked: number;
  /**
   * Left after eligibility, closed listings, required pay minimums and
   * what the person already acted on (rejected, applied).
   */
  passed_eligibility: number;
  /**
   * Of those, the ones ranked maybe or better.
   */
  plausible: number;
  /**
   * Shown now.
   */
  shown: number;
  /**
   * Of those, the ones worth reviewing or a strong fit.
   */
  worth_reviewing: number;
}
/**
 * Opportunities left out, by why.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "NotShown".
 */
export interface NotShown {
  below_pay_minimum: number;
  /**
   * Beyond the limit.
   */
  beyond_limit: number;
  closed: number;
  /**
   * Eligibility not confirmed, and the person hides such jobs.
   */
  eligibility_unconfirmed?: number;
  in_pipeline: number;
  ineligible: number;
  /**
   * Ranked maybe or low priority (`all_tiers` shows them).
   */
  lower_tiers: number;
  /**
   * Pay not published (or not comparable), and the person hides such
   * jobs.
   */
  pay_unknown?: number;
  rejected: number;
  /**
   * The posting contradicts something the person requires: a company
   * or team kind, their work setup, relocation, a remote geography.
   */
  unmet_requirement?: number;
}
/**
 * One shortlisted opportunity.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ShortlistItem".
 */
export interface ShortlistItem {
  company: string;
  compensation: CompensationView2;
  /**
   * What to consider: caveats, then unknowns (up to 3).
   */
  consider: string[];
  department?: string | null;
  eligibility: EligibilityBrief;
  /**
   * Useful practical facts (pay reaching the person's target, remote
   * from where they want). Never reasons for fit.
   */
  facts?: string[];
  /**
   * How well it fits what the person wants: `strong`, `plausible`,
   * `insufficient` or `poor` (the tier, in fit's words).
   */
  fit?: string | null;
  /**
   * `opp_…`: the logical opportunity (one job, however many sources
   * list it). Use it with every other tool.
   */
  id: string;
  /**
   * Every location the listing names, primary first.
   */
  locations?: string[];
  /**
   * The suggested next step, as a CLI command.
   */
  next_step: string;
  recommendation: Recommendation;
  /**
   * What to check first, when it applies.
   */
  recommendation_note?: string | null;
  remote?: boolean | null;
  /**
   * Shown by the CLI (`opp_1a2b3c4d`); accepted back while unique.
   */
  short_id: string;
  /**
   * How many sources list it.
   */
  sources: number;
  /**
   * Role · level · stack · domain · pay · where.
   */
  summary: string;
  team?: string | null;
  tier: FitTier;
  title: string;
  /**
   * Things to check before spending time on it (pay not published,
   * remote scope unclear, travel expected): the person's own
   * requirements first, up to 3.
   */
  to_check?: string[];
  /**
   * The lines of `consider` about what the posting doesn't say
   * (unknowns, not cautions); the others are caveats.
   */
  unknowns?: string[];
  verification: VerificationBrief;
  /**
   * Why it may be worth the person's time (up to 4; verification and
   * eligibility are in their own fields).
   */
  why: string[];
  /**
   * `remote`, `hybrid` or `onsite`, as the listing says.
   */
  workplace?: string | null;
}
/**
 * Published pay, as facts.
 */
export interface CompensationView2 {
  /**
   * Each published range in words ("USD 140,000 – 180,000 per year").
   * A range whose currency is only an ambiguous symbol says so; it is
   * never read as a low number.
   */
  ranges: string[];
  /**
   * `published`, `not_published` or `not_observed`.
   */
  status: string;
  /**
   * The source's own summary text, verbatim.
   */
  summary?: string | null;
  /**
   * Whether the facts come from a verification (`true`) or from
   * discovery (`false`).
   */
  verified: boolean;
  verified_at?: string | null;
}
/**
 * What importing a LinkedIn export or a GitHub account changed.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SourceImportResult".
 */
export interface SourceImportResult {
  claims: TallyView;
  /**
   * Statements that disagree with another source (different dates for
   * one position); each waits for review.
   */
  conflicts: number;
  education: TallyView;
  experiences: TallyView;
  /**
   * The profile had no such source before.
   */
  first_import: boolean;
  /**
   * Confirmed claims found again (still confirmed).
   */
  kept_confirmed: number;
  /**
   * Rejected claims found again (still rejected, never used).
   */
  kept_rejected: number;
  /**
   * What was imported: the export's file name, or `github.com/<login>`.
   */
  label: string;
  /**
   * Claims now waiting for the person's review.
   */
  needs_review: number;
  /**
   * Doubts about particular rows or records.
   */
  notes: string[];
  /**
   * Records where the person's own edits were kept.
   */
  preserved_edits: number;
  /**
   * Parts that could not be read (the rest was imported).
   */
  problems: string[];
  profile: ProfileView2;
  projects: TallyView;
  /**
   * What Narrow read ("3 positions", "12 repositories").
   */
  read: string[];
  /**
   * Confirmed claims whose wording changed: they need confirming again.
   */
  reconfirm: number;
  skills: TallyView;
  /**
   * What it deliberately did not use ("2 forks", "38 other files in
   * the export, never opened").
   */
  skipped: string[];
  /**
   * `linkedin` or `github`.
   */
  source: string;
  /**
   * Confirmed claims no source supports any more.
   */
  stale_confirmed: number;
  /**
   * The same content as the last import: nothing new to read.
   */
  unchanged: boolean;
}
/**
 * The profile after the import.
 */
export interface ProfileView2 {
  /**
   * Always true: names and contact details are not part of this view.
   */
  contact_details_omitted: boolean;
  /**
   * Imported sources (resumes, a LinkedIn export, a GitHub account),
   * the current ones first.
   */
  documents?: DocumentSummary[];
  domains: Signal[];
  education?: EducationSummary[];
  experiences: ExperienceSummary[];
  /**
   * What is missing or uncertain.
   */
  gaps: string[];
  headline?: string | null;
  /**
   * Where the person lives, as they wrote it (eligibility depends on it).
   */
  location?: string | null;
  /**
   * Claims needing the person's review (the first few).
   */
  needs_review: UnresolvedClaim[];
  needs_review_total: number;
  /**
   * Seniority and ownership signals (led, mentored, founding).
   */
  ownership_signals: Signal[];
  /**
   * Preferences in effect.
   */
  preferences: PreferenceView[];
  projects?: ProjectSummary[];
  /**
   * Kinds of engineering role the experience shows (backend, platform).
   */
  role_signals: Signal[];
  /**
   * What the person said, verbatim.
   */
  statements: StatementView[];
  summary?: string | null;
  /**
   * Strongest evidence first.
   */
  technologies: TechnologyEvidence[];
}
/**
 * What taking a source out did.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "SourceRemovalResult".
 */
export interface SourceRemovalResult {
  /**
   * Claims only this source supported, deleted.
   */
  claims_deleted: number;
  /**
   * Claims other sources still support (their provenance moved there).
   */
  claims_kept: number;
  /**
   * Claims only this source supported that the person had confirmed,
   * rejected or rewritten: kept without a source (confirmations need
   * renewing before use).
   */
  decisions_kept: number;
  needs_review: number;
  profile: ProfileView;
  /**
   * Records only this source supported, deleted.
   */
  records_deleted: number;
  /**
   * Records other sources (or the person) still support.
   */
  records_kept: number;
  /**
   * `linkedin` or `github`.
   */
  source: string;
}
/**
 * The taste profile, as the Preferences page shows it.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteProfileView".
 */
export interface TasteProfileView {
  /**
   * What they tend to avoid.
   */
  avoid: TasteLineView[];
  /**
   * When they last said it looks right.
   */
  confirmed_at?: string | null;
  /**
   * Whether they can take a job: work setup, where they live and may
   * work, relocation, pay floor.
   */
  constraints: ConstraintView[];
  interpretation?: InterpretationView | null;
  /**
   * Patterns learned from feedback, kept apart from what they said.
   */
  learned: TasteItemView[];
  /**
   * What the person is looking for, in their words.
   */
  looking_for?: string | null;
  /**
   * `description` (what they described), `statements` (their earlier
   * words, not yet interpreted as a description), or absent.
   */
  looking_for_source?: string | null;
  /**
   * The summary has statements Narrow read that they haven't reviewed.
   */
  needs_confirmation: boolean;
  /**
   * Said not to matter.
   */
  neutral: TasteItemView[];
  reader: ReaderView;
  /**
   * Statements they removed (never read again).
   */
  removed: TasteItemView[];
  /**
   * What Narrow understands they want, one line per dimension.
   */
  understood: TasteLineView[];
  /**
   * Weak inferences, not part of the summary unless confirmed.
   */
  unsure: TasteItemView[];
}
/**
 * One line of the summary: statements about one dimension that lean the
 * same way ("Backend engineering · Platform engineering").
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteLineView".
 */
export interface TasteLineView {
  dimension: string;
  /**
   * Every statement of the line is Narrow's inference (from the profile
   * or feedback), not something the person said.
   */
  inferred: boolean;
  items: TasteItemView[];
  text: string;
}
/**
 * One statement of the taste profile.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteItemView".
 */
export interface TasteItemView {
  /**
   * Sources that point the other way.
   */
  against?: TasteSourceView[];
  /**
   * Where it comes from, in a few words: "You said", "Narrow's reading
   * of your words", "Inferred from your profile", "Learned from your
   * feedback", "From your earlier settings".
   */
  basis: string;
  /**
   * `low`, `medium` or `high`.
   */
  confidence: string;
  /**
   * `seniority`, `work_shape`, `specialization`, `ownership`,
   * `company`, `team`, `culture`, `domain`, `technology`,
   * `work_style`, `other`.
   */
  dimension: string;
  explanation?: string | null;
  /**
   * `taste_…`: pass it to confirm, correct or remove it.
   */
  id: string;
  /**
   * `rules/1`, `model/anthropic:claude-opus-5-5`.
   */
  interpreter?: string | null;
  /**
   * `stated`, `interpreted`, `profile`, `learned` or `legacy`.
   */
  origin: string;
  /**
   * What Narrow had read before the person corrected it.
   */
  original?: string | null;
  /**
   * `prefer`, `open`, `avoid` or `neutral`.
   */
  polarity: string;
  /**
   * `unreviewed`, `confirmed`, `corrected` or `removed`.
   */
  review: string;
  sources: TasteSourceView[];
  /**
   * "Small technical teams".
   */
  text: string;
  /**
   * The canonical value (`small_team`) or the person's words
   * normalized.
   */
  value: string;
}
/**
 * Where one statement comes from, readable.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteSourceView".
 */
export interface TasteSourceView {
  /**
   * `words`, `preference`, `evidence`, `feedback` or `person`.
   */
  kind: string;
  /**
   * "You wrote: “small technical teams”".
   */
  text: string;
}
/**
 * A practical constraint: whether the person can take a job, not
 * whether they'd want it. Read from their preferences.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ConstraintView".
 */
export interface ConstraintView {
  /**
   * The preferences behind it (`pref_…`); empty when read from the
   * resume.
   */
  ids: string[];
  /**
   * `work_setup`, `location`, `authorization`, `relocation`,
   * `remote_geography`, `timezone`, `sponsorship`, `engagement`,
   * `pay_floor`, `pay_target`, `policy`.
   */
  kind: string;
  /**
   * `requirement` (a posting that states otherwise is left out) or
   * `preference`.
   */
  layer: string;
  /**
   * "Remote only", "Based in São Paulo, Brazil".
   */
  text: string;
}
/**
 * How the description was last interpreted.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "InterpretationView".
 */
export interface InterpretationView {
  /**
   * What was unclear, for the person to settle.
   */
  ambiguities: string[];
  at: string;
  /**
   * Practical constraints the words mentioned (never taste).
   */
  constraints_noted: string[];
  interpreter: string;
  note?: string | null;
  /**
   * `read`, or `fallback` when a model couldn't be used and the rules
   * read instead.
   */
  outcome: string;
  /**
   * Statements the interpreter produced that failed validation.
   */
  rejected: number;
  summary?: string | null;
}
/**
 * What reads the person's words.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "ReaderView".
 */
export interface ReaderView {
  /**
   * `model` or `rules`.
   */
  kind: string;
  /**
   * `rules/1`, `model/anthropic:claude-opus-5-5`.
   */
  name: string;
  /**
   * Why a configured model isn't used.
   */
  note?: string | null;
}
/**
 * The answer of a change.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteUpdateResult".
 */
export interface TasteUpdateResult {
  /**
   * `describe`, `reinterpret`, `confirm`, `correct`, `neutral`,
   * `remove`, `add`.
   */
  action: string;
  /**
   * Something changed.
   */
  changed: boolean;
  /**
   * The words were interpreted by this call (false when the same input
   * was already interpreted).
   */
  interpreted: boolean;
  /**
   * For a description: the practical constraints and structured
   * preferences read from the words.
   */
  preferences?: PreferenceUpdateResult | null;
  profile: TasteProfileView1;
}
/**
 * The profile afterwards.
 */
export interface TasteProfileView1 {
  /**
   * What they tend to avoid.
   */
  avoid: TasteLineView[];
  /**
   * When they last said it looks right.
   */
  confirmed_at?: string | null;
  /**
   * Whether they can take a job: work setup, where they live and may
   * work, relocation, pay floor.
   */
  constraints: ConstraintView[];
  interpretation?: InterpretationView | null;
  /**
   * Patterns learned from feedback, kept apart from what they said.
   */
  learned: TasteItemView[];
  /**
   * What the person is looking for, in their words.
   */
  looking_for?: string | null;
  /**
   * `description` (what they described), `statements` (their earlier
   * words, not yet interpreted as a description), or absent.
   */
  looking_for_source?: string | null;
  /**
   * The summary has statements Narrow read that they haven't reviewed.
   */
  needs_confirmation: boolean;
  /**
   * Said not to matter.
   */
  neutral: TasteItemView[];
  reader: ReaderView;
  /**
   * Statements they removed (never read again).
   */
  removed: TasteItemView[];
  /**
   * What Narrow understands they want, one line per dimension.
   */
  understood: TasteLineView[];
  /**
   * Weak inferences, not part of the summary unless confirmed.
   */
  unsure: TasteItemView[];
}
/**
 * The answer of `get_taste`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteView".
 */
export interface TasteView {
  /**
   * Patterns the evidence contradicts: not used.
   */
  contradictory: LearnedView[];
  controls: PreferenceControls;
  /**
   * Patterns about something the person also stated: what they said is
   * used.
   */
  covered_by_stated: LearnedView[];
  /**
   * Patterns with too little evidence to use yet.
   */
  emerging: LearnedView[];
  /**
   * Pieces of feedback (not counting "looked at").
   */
  feedback_events: number;
  /**
   * Reasons about single jobs, not generalized.
   */
  job_notes: JobNoteView[];
  /**
   * Patterns learned from feedback that affect ranking now.
   */
  learned: LearnedView[];
  /**
   * Jobs with feedback.
   */
  opportunities: number;
  /**
   * What the person said: preferences in effect (they always win over
   * anything learned).
   */
  stated: PreferenceView[];
  /**
   * The person's statements, verbatim, with what was not understood.
   */
  statements: StatementView[];
  /**
   * Reasons nothing could be read from, kept as written.
   */
  unread_reasons: UnreadReasonView[];
}
/**
 * A pattern learned from feedback.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "LearnedView".
 */
export interface LearnedView {
  /**
   * Evidence against it, newest first.
   */
  against: TasteEvidenceView[];
  /**
   * Whether the feedback agrees with what they said (explicit patterns).
   */
  agrees?: boolean | null;
  /**
   * "2 reasons in your words and 1 action without a reason".
   */
  basis: string;
  /**
   * `tentative`, `established` or `strong` (active patterns).
   */
  confidence?: string | null;
  /**
   * `role`, `domain`, `company`, `technology`, …
   */
  dimension: string;
  /**
   * `prefer` or `avoid`: the way the evidence leans.
   */
  direction: string;
  /**
   * `role:sre`, `domain:developer_tools`, …
   */
  key: string;
  last_reinforced: string;
  /**
   * Distinct jobs behind the support.
   */
  opportunities: number;
  /**
   * Reasons in the person's words among the support.
   */
  reasons: number;
  /**
   * What the person said about it (explicit patterns).
   */
  stated?: string | null;
  /**
   * `active` (used in ranking), `mixed` (contradictory, not used),
   * `not_enough` (too little evidence yet) or `explicit` (the person
   * said something about it, which is used instead).
   */
  status: string;
  /**
   * Evidence for it, newest first.
   */
  support: TasteEvidenceView[];
  /**
   * The value, readable: `SRE / DevOps`, `large companies`.
   */
  value: string;
}
/**
 * One piece of feedback behind a learned pattern.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TasteEvidenceView".
 */
export interface TasteEvidenceView {
  /**
   * `save`, `reject`, `applied`, `like`, …
   */
  action: string;
  at: string;
  company: string;
  /**
   * `reason` (the person's words) or `behavior` (what they did).
   */
  kind: string;
  /**
   * `opp_…` the feedback was about.
   */
  opportunity: string;
  /**
   * The fact of the job it counted for (behavior), or the part of the
   * reason that was read.
   */
  read_as: string;
  /**
   * The reason, verbatim (reasons only).
   */
  reason?: string | null;
  /**
   * One line, for display.
   */
  summary: string;
  title: string;
}
/**
 * The same preferences as structured controls (work setup,
 * relocation, location, pay, company and team), each in its layer.
 */
export interface PreferenceControls {
  company: CompanyControls;
  location: LocationControls;
  pay: PayControls;
  work: WorkControls;
}
/**
 * Team size, company size and stage, kept apart.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "CompanyControls".
 */
export interface CompanyControls {
  items: CompanyControl[];
}
/**
 * One kind of team or company.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "CompanyControl".
 */
export interface CompanyControl {
  /**
   * `must_have`, `nice_to_have`, `avoid` or `off`.
   */
  importance: string;
  /**
   * `requirement`, `preference`, or `none` when off.
   */
  layer: string;
  record?: PreferenceView | null;
  /**
   * `team`, `company_size` or `stage`: a company's size never stands in
   * for a team's, and neither is a stage.
   */
  scope: string;
  /**
   * `small_team`, `small_company`, `large_company`, `early_stage`,
   * `startup`, `scaleup`.
   */
  value: string;
}
/**
 * Where the person lives and may work, and what to do when eligibility
 * is unclear. The job's own location, its remote scope, the person's work
 * authorization and relocation are separate things, kept apart.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "LocationControls".
 */
export interface LocationControls {
  /**
   * Countries or regions the person stated they may already work in.
   */
  authorized_in: PlaceControl[];
  /**
   * Where the person lives, as written (from the preference, else the
   * resume header).
   */
  home?: string | null;
  /**
   * `preference` or `resume`.
   */
  home_basis?: string | null;
  /**
   * The country Narrow reads it as ("Brazil"); absent when unrecognized.
   */
  home_country?: string | null;
  /**
   * The `current_location` preference, when set.
   */
  home_record?: PreferenceView | null;
  /**
   * Geographies remote roles should be open to, with their stance.
   */
  remote_geography: PlaceControl[];
  /**
   * Remote scopes that include where the person lives, broadest first
   * ("anywhere", "the Americas", "Latin America", "South America",
   * "Brazil"). A posting that says only "Remote" is none of these.
   */
  remote_open_to_you: string[];
  /**
   * `show` (marked unresolved; the default) or `hide` (until
   * eligibility is confirmed).
   */
  unclear_eligibility: string;
  unclear_eligibility_record?: PreferenceView | null;
}
/**
 * A place the person named, as written and as Narrow reads it.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PlaceControl".
 */
export interface PlaceControl {
  /**
   * Stable code of the place (`worldwide`, `americas`, `latam`, `BR`),
   * when recognized.
   */
  code?: string | null;
  /**
   * As written.
   */
  place: string;
  /**
   * How Narrow reads it ("Brazil", "Latin America", "anywhere"); absent
   * when it doesn't recognize the place, which then never counts as
   * including anywhere.
   */
  read_as?: string | null;
  record: PreferenceView;
}
/**
 * A minimum (a requirement) and a target (a preference), and what to do
 * with jobs whose pay isn't published.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PayControls".
 */
export interface PayControls {
  minimum: PayControl[];
  target: PayControl[];
  /**
   * `show` (marked unresolved; the default) or `hide`.
   */
  unknown_pay: string;
  unknown_pay_record?: PreferenceView | null;
}
/**
 * One pay figure.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PayControl".
 */
export interface PayControl {
  amount: number;
  /**
   * `employment` or `contract`; absent for both.
   */
  applies_to?: string | null;
  /**
   * ISO code; absent when the person's words didn't say (never
   * assumed: until it is set, pay isn't compared).
   */
  currency?: string | null;
  /**
   * `year`, `month`, `day` or `hour`.
   */
  period: string;
  record: PreferenceView;
}
/**
 * Remote, hybrid or on-site, and relocation: two separate answers.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "WorkControls".
 */
export interface WorkControls {
  /**
   * The stored work modes in words, when `setup` is `custom`.
   */
  custom?: string | null;
  /**
   * `not_willing`, `open`, `only_selected` or `unset`.
   */
  relocation: string;
  /**
   * The places, when `only_selected`.
   */
  relocation_only_to: string[];
  relocation_record?: PreferenceView | null;
  /**
   * `remote_only`, `prefer_remote`, `hybrid_okay`, `onsite_okay`,
   * `no_preference`, or `custom` when the stored work modes are none of
   * those (a statement said "hybrid, not on-site"; see `custom`).
   */
  setup: string;
  /**
   * `requirement`, `preference`, or `none` (no preference).
   */
  setup_layer: string;
  /**
   * The work-mode preferences behind the answer.
   */
  setup_records: PreferenceView[];
}
/**
 * A reason about one job only (not generalized).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "JobNoteView".
 */
export interface JobNoteView {
  action: string;
  at: string;
  direction: string;
  opportunity: string;
  /**
   * What it was read as ("avoid: this domain").
   */
  read_as: string;
  /**
   * The reason, verbatim.
   */
  reason: string;
}
/**
 * A reason nothing could be read from, kept as written.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "UnreadReasonView".
 */
export interface UnreadReasonView {
  action: string;
  at: string;
  company: string;
  opportunity: string;
  reason: string;
  title: string;
}
/**
 * `GET /api/v1/tokens`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "TokenList".
 */
export interface TokenList {
  tokens: TokenView[];
}
/**
 * `PUT /api/v1/notifications`. Absent fields are left as they are.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "UpdateNotificationsRequest".
 */
export interface UpdateNotificationsRequest {
  /**
   * `immediate` or `daily`.
   */
  cadence?: string | null;
  /**
   * The address to notify. A new address is sent a confirmation link;
   * nothing else is sent to it until it is confirmed.
   */
  email?: string | null;
  email_enabled?: boolean | null;
  /**
   * Send the confirmation link again.
   */
  resend_confirmation?: boolean;
}
/**
 * Arguments of `update_preferences`. Give at least one of `statement`,
 * `set` or `remove`.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "UpdatePreferencesParams".
 */
export interface UpdatePreferencesParams {
  /**
   * Preference (pref_…) or statement (stmt_…) ids to remove.
   */
  remove?: string[];
  /**
   * Precise preferences to set.
   */
  set?: PreferenceInput[];
  /**
   * What the person wants, in their own words, e.g. "I want small
   * product teams, backend or platform work, remote from Brazil, at
   * least USD 120k". Stored verbatim; what JobHunt understands from it
   * is returned, including the parts it didn't understand.
   */
  statement?: string | null;
}
/**
 * The answer of `verify_job` (and `narrow verify --json`).
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "VerificationReport".
 */
export interface VerificationReport {
  application: ApplicationState;
  application_url?: string | null;
  /**
   * Who publishes the listing (`employer_configured_ats`, …).
   */
  authority: string;
  company: string;
  compensation: CompensationView;
  /**
   * `None` without a profile.
   */
  eligibility?: EligibilityDetail | null;
  /**
   * `opp_…`.
   */
  id: string;
  /**
   * The latest attempt at the record the state rests on.
   */
  last_attempt_at?: string | null;
  /**
   * The latest attempt that reached an answer.
   */
  last_success_at?: string | null;
  /**
   * The listing state one verification attempt found.
   */
  listing: "active" | "closed" | "unreachable" | "ambiguous" | "unknown";
  /**
   * Trusted and the person appears able to take it.
   */
  recommendable: boolean;
  /**
   * Records whose recent attempt (within the reuse window) was reused
   * instead of asking the source again.
   */
  reused: number;
  /**
   * Every source record with its latest attempt.
   */
  sources: SourceRecordView[];
  title: string;
  /**
   * What is uncertain: unknowns from the attempts, failures, and
   * disagreements between sources.
   */
  uncertainty: string[];
  verification: VerificationBrief;
}
/**
 * Every structured control, read from the preferences in effect.
 *
 * This interface was referenced by `JobHuntApi`'s JSON-Schema
 * via the `definition` "PreferenceControls".
 */
export interface PreferenceControls1 {
  company: CompanyControls;
  location: LocationControls;
  pay: PayControls;
  work: WorkControls;
}
